version: 2.0
jobs:
  build_clang:
    docker:
      - image: pcppcp/anyledger:latest
    environment:
        CC: clang
        CXX: clang++
        CMAKE_CXX_FLAGS: -fsanitize=address
        CMAKE_C_FLAGS: -fsanitize=address
    steps:
      - checkout
      - run: .circleci/run_test.sh
  build_gcc_6:
    docker:
      - image: pcppcp/anyledger:latest
    steps:
      - checkout
      - run: .circleci/run_test.sh
  build_zephyr:
    docker:
      - image: pcppcp/anyledger:latest
    steps:
      - checkout
      - run: .circleci/build_zephyr_nrf52840_pca10056.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_zephyr
      - build_clang
